### ISSUE TITLE
download function raises Uncaught TypeError: t.getX is not a function

### ISSUE THREAD

**Issue by tommyJin** [ivmartel/dwv-jqui#70]
Hi, happy new year,
When I draw something and try to download the state.json file, the error occurs. I've tried the v0.6.0 and v0.7.0-beta. But I found the live demo v0.5.1 is ok with the download function[https://ivmartel.github.io/dwv-jqui/demo/stable/index.html]

```
Uncaught TypeError: t.getX is not a function
    at A.io.State.toJSON (dwv.min.js:3)
    at A.App.getState (dwv.min.js:3)
    at HTMLAnchorElement.toggleSaveState.onclick (appgui.js:155)
```

And I traced with the error and found it is located in the file state.js on line 52  _position: [position.getX(), position.getY(), position.getZ()],_ of the dwv project [state.js#L52](https://github.com/ivmartel/dwv/blob/v0.30.7/src/io/state.js#L52)

Thx.

**Comment by tommyJin** [comment]
Could u pls update the npm repo version? I redo npm install & npm run dev, and the question remains.
In the package.json, the dependency of dwv version is _"dwv": "0.30.7"_
Thx.

**Comment by ivmartel** [comment]
I'll check if everything is ok and then create a release.

**Comment by tommyJin** [comment]
Cheers!

**Comment by ivmartel** [comment]
Just released dwv `0.30.8`, check [demo/trunk/index.html](https://ivmartel.github.io/dwv-jqui/demo/trunk/index.html) for an updated dwv-jqui.
